POST http://localhost:5000/api/skill
Content-Type: application/json

{
    "name": "GraphQL"
}

###
GET http://localhost:5000/api/skill

###
DELETE http://localhost:5000/api/skill
Content-Type: application/json

{
    "id": 1
}

###
PUT http://localhost:5000/api/skill
Content-Type: application/json

{
    "id": 2,
    "newData": {
        "name": "PHP"
    }
}