POST http://localhost:5000/api/wilder
Content-Type: application/json

{
    "name": "Jane Doe"
}

###
GET http://localhost:5000/api/wilder

###
DELETE http://localhost:5000/api/wilder
Content-Type: application/json

{
    "id": 1
}

###
PUT http://localhost:5000/api/wilder
Content-Type: application/json

{
    "id": 2,
    "newData": {
        "name": "John"
    }
}

###
PUT http://localhost:5000/api/wilder/addSkill
Content-Type: application/json

{
    "wilderName": "John",
    "skillName": "Javascript"
}