POST http://localhost:5000/api/wilder
Content-Type: application/json

{
    "name": "Jean Dupont",
    "email": "jean.dupont@exemple.fr",
    "city": "Toulouse"
}

###
GET http://localhost:5000/api/wilder

###
DELETE http://localhost:5000/api/wilder
Content-Type: application/json

{
    "id": 1
}

###
PUT http://localhost:5000/api/wilder/1
Content-Type: application/json

{
    "city": "Lille"
}

###
POST http://localhost:5000/api/wilder/2/skill/2/add